### PR TITLE
On jpm init, README.md populated with addon title and description

### PR DESCRIPTION
**Pull request by bobbyrne01**

### CODE REVIEW

**Comment by erikvold** [comment]
looks good to me, just need a test.

**Comment by bobbyrne01** [comment]
@erikvold I've updated the `init` tests mentioned below which should cover this functionality. If I've missed anything just let me know.

test.init.js ..

 * creates package.json with defaults
 * copies in default README.md if it DNE

**Comment by erikvold** [comment]
So there is a test failure on travis:
  125 passing (3m)
  1 failing
  1) jpm init does not copy in default README.md if it exists:
     Error: timeout of 20000ms exceeded
      at null.<anonymous> (/home/travis/build/mozilla/jpm/node_modules/mocha/lib/runnable.js:159:19)
      at Timer.listOnTimeout (timers.js:88:15)

We will need to update that failing test first

**Comment by bobbyrne01** [comment]
Looks ok locally now ..

✓ does not copy in default README.md if it exists (266ms)

**Pull request merged**
